### ISSUE TITLE
Migration from mongodb-extended-json

### ISSUE THREAD

**Issue by Ognian** [mongodb-js/mongodb-extjson#20]
As https://github.com/mongodb-js/extended-json refers to this lib, would it be possible to add a few lines in the readme on how to transition?
I see that there is now a `deserialize` function but ` stringify` has different arguments ...
Thanks
Ognian

**Comment by imlucas** [comment]
The latest release of `bson@4` matches the API's and mongodb/js-bson#347 the new option for legacy mode should take care of any semantic issues. Let me know if you run into any roadblocks.

**Comment by Ognian** [comment]
@imlucas tried to migrate directly from   ```const EJSON = require('mongodb-extended-json')``` to ```const { EJSON } = require('bson')``` and started with ```EJSON.deserialize(xxxxx, { legacy: true, relaxed: false })```. I'm using the last 'json' version 4.0.3 (where your last pull request is still not included), and found the following problem: if `xxxxx` is a JSON Object where i.e. the _id is already an ObjectId object and 'deserialize` is called to convert other EJSON objects to native or BSON objects the ObjectId is converted to a String instead of left untouched... This is a different behaviour then with mongoldb-extended-json deserialize....

**Comment by imlucas** [comment]
@Ognian not sure I follow and want to understand exactly. Any chance you could link to script or paste here to reproduce?

**Comment by Ognian** [comment]
```

const { ObjectID } = require('mongodb')
const EJSON = require('mongodb-extended-json')

const { EJSON: EJSONnew } = require('bson')

const src = {
  _id: new ObjectID(),
  date: { $date: new Date().toISOString() }
}

const oldDeserialize = EJSON.deserialize(src)
const newDeserialize = EJSONnew.deserialize(src)

console.log(`oldDeserialize:`, oldDeserialize)
console.log(`newDeserialize:`, newDeserialize)

```
console log shows:
```
oldDeserialize: { _id: 5e2088ea68406e7ca1ed3222, date: 2020-01-16T16:01:46.218Z }
newDeserialize: { _id: '5e2088ea68406e7ca1ed3222', date: 2020-01-16T16:01:46.218Z }
```
the second _id is a string!! not an ObjectID object...
the debugger shows it even better:
![image](https://user-images.githubusercontent.com/1231174/72541099-3b4c9500-3882-11ea-96b7-284b789a3c0e.png)

**Comment by Ognian** [comment]
@imlucas have you been able to reproduce with the code from the previous post?
