### ISSUE TITLE
EJSON.parse inconsistent double parsing in relaxed mode

### ISSUE THREAD

**Issue by jandorfer** [mongodb-js/mongodb-extjson#24]
While in "relaxed"/non-strict parsing mode when parsing non-integer values that are not in extended json format the result will be a bson Double object. That is inconsistent with the [bson spec for relaxed parsing](https://github.com/mongodb/specifications/blob/master/source/extended-json.rst#relaxed-extended-json-example) which indicates the output of a parsed double should be a raw js Number.

It's also internally inconsistent as parsing of doubles serialized in extended json format do come out as plain Numbers. Put a plain number in, get a ext-json Double object out. Put a ext-json formatted double in, get a plain Number out.

```js
parse('{"Double": 42.42, "DoubleEJSON": { "$numberDouble": "42.42" }}', {relaxed: true})
```
```js
{ 
    "Double": {
        value: "42.42"
        _bsontype: "Double"
    }
    "DoubleEJSON": 42.42
}
```

Looks to me like [this line](https://github.com/mongodb-js/mongodb-extjson/blob/v3.0.3/lib/ext_json.js#L59) should be checking for relaxed parsing mode.

**Comment by mbroadst** [comment]
Hi @jandorfer, thanks for pointing this out. We've actually recently merged `mongodb-extjson` with `js-bson`, and this was one of the [fixes](https://github.com/mongodb/js-bson/blob/master/lib/extended_json.js#L41) that made it into the 4.x release of that package. We've been a little slow to fully deprecate this library, but that is the current guidance.

**Comment by jandorfer** [comment]
Ah, alright, thanks!
