### ISSUE TITLE
Disparity in how stringify handles strings

### ISSUE THREAD

**Issue by PrashanthCorp** [mongodb-js/mongodb-extjson#28]
In the older `mongodb-extended-json`, code like this works fine: 

`
let EJSON = require("mongodb-extended-json")
EJSON.stringify("my-collection")
> output - '"my-collection"' 
`

Now, the same stringify function call gives an error: 
`Error: not an object instance`

I didn't see this mentioned anywhere. Is this side-effect intended?

**Comment by mbroadst** [comment]
@PrashanthCorp In v4 of [js-bson](https://github.com/mongodb/js-bson), we rolled extended json support directly into the BSON library. This project is currently deprecated in favor of using `js-bson`. Please test that library, and open a ticket against our JIRA if you continue to have issues. I'll make sure to note the deprecation in the README
